# Generated by Django 4.2.1 on 2023-05-31 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='date',
        ),
        migrations.AddField(
            model_name='events',
            name='end_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, max_length=128, verbose_name='Дата окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, max_length=128, verbose_name='Дата начала'),
            preserve_default=False,
        ),
    ]
