# Generated by Django 4.2.1 on 2023-05-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_events_date_events_end_date_events_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(max_length=128, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateField(max_length=128, verbose_name='Дата начала'),
        ),
    ]
