# Generated by Django 4.2.1 on 2023-06-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_events_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='tickets_link',
            field=models.CharField(default='', max_length=512, verbose_name='Ссылка на покупку билетов'),
        ),
        migrations.AddField(
            model_name='events',
            name='vk_link',
            field=models.CharField(default='', max_length=512, verbose_name='Ссылка на встречу ВК'),
        ),
    ]
