# Generated by Django 4.2.1 on 2023-06-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_events_tickets_link_alter_events_vk_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='tickets_link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на покупку билетов'),
        ),
        migrations.AlterField(
            model_name='events',
            name='vk_link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на встречу ВК'),
        ),
    ]
