# Generated by Django 4.2.1 on 2023-06-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_events_tickets_link_alter_events_vk_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
